import assert from 'node:assert/strict';
import test from 'node:test';
import { buildPrimitiveCandidates, resolveIntent, resolvePrimaryPrototype, resolvePrimaryTask, resolvePrimitiveActivation, TASK_TO_PROTOTYPE } from '../../src/v4/intent-resolver';
import { PLAYER_TASKS, type PlayerTask } from '../../src/v4/intent-contract';

const winners: Array<[string, PlayerTask, string]> = [
 ['bg3 classes','choice-comparison','P3'],['bg3 companions','collection-browse','P2'],['bg3 adamantine forge','location','P5'],['bg3 quests','progression','P6'],['bg3 weapons','collection-browse','P2'],['white lady hollow knight','entity-lookup','P1'],['dream nail','entity-lookup','P1'],['hollow knight charms','collection-browse','P2'],['hornet hollow knight','entity-lookup','P1'],['minecraft villager','entity-lookup','P1'],['minecraft cake','entity-lookup','P1'],['minecraft mobs','collection-browse','P2'],['best minecraft enchantments','recommendation','P8'],['minecraft enchantments','mechanics','P7'],['stardew valley farming','progression','P6'],['stardew valley fall','planning','P10'],['stardew valley crafting','procedure','P4'],['stardew valley summer seeds','entity-lookup','P1'],['stardew valley cauliflower','entity-lookup','P1'],['poe currency','mechanics','P7'],['poe ascendancy class','choice-comparison','P3'],['poe skill gems','mechanics','P7'],['terraria bosses','collection-browse','P2'],['terraria hardmode guide','progression','P6'],['terraria wings','collection-browse','P2'],['terraria npcs','collection-browse','P2'],['terraria shimmer','mechanics','P7'],['diablo 4 builds','recommendation','P8'],['diablo 4 build planner','tool-database','P9'],['diablo 4 uniques','tool-database','P9'],['no hesitation','entity-lookup','P1'],['eyasluna','entity-lookup','P1'],['matador 64','entity-lookup','P1'],['destiny 2 god rolls','recommendation','P8'],['destiny 2 loadouts','tool-database','P9'],['ark taming','procedure','P4'],['ark resource map the island','location','P5'],['ark creatures','collection-browse','P2'],['ark bosses','progression','P6'],['satisfactory dedicated server','procedure','P4'],['satisfactory blueprints','procedure','P4'],['satisfactory power','mechanics','P7'],['satisfactory fluids guide','mechanics','P7'],['satisfactory train throughput','mechanics','P7'],
];
test('taxonomy mapping: all 10 tasks map to the frozen Prototype vocabulary',()=>{ assert.deepEqual(Object.keys(TASK_TO_PROTOTYPE).sort(),[...PLAYER_TASKS].sort()); for(const task of PLAYER_TASKS) assert.equal(resolvePrimaryPrototype(task),TASK_TO_PROTOTYPE[task]); });
test('taxonomy mapping: 44 certified winners retain their known task to Prototype mapping',()=>{ for(const [,task,prototype] of winners) assert.equal(resolvePrimaryPrototype(task),prototype); });
test('winner layer count is explicit',()=>assert.equal(winners.length,44));
test('resolver regression: inference uses query/signals and does not receive final task',()=>{
 const cases=[['diablo 4 build planner','operate a build workspace','P9','query-semantics'],['terraria','browse bosses','P2','answer-shape'],['terraria','choose the next boss','P3','answer-shape'] as const];
 const first=resolveIntent({query:cases[0][0],playerProblem:cases[0][1]}); assert.equal(first.prototype,cases[0][2]); assert.equal(first.resolution.basis,cases[0][3]);
 const second=resolveIntent({query:cases[1][0],playerProblem:cases[1][1],evidence:{answerShape:'catalog'}}); assert.equal(second.prototype,cases[1][2]); assert.equal(second.resolution.basis,'answer-shape');
 const third=resolveIntent({query:'terraria',playerProblem:cases[2][1],evidence:{answerShape:'comparison'}}); assert.equal(third.prototype,cases[2][2]); assert.equal(third.resolution.basis,'answer-shape');
});
test('precedence: explicit task outranks query semantics',()=>{const r=resolvePrimaryTask({query:'terraria bosses',playerProblem:'choose one',primaryTask:'choice-comparison'}); assert.equal(r.task,'choice-comparison'); assert.equal(r.basis,'primary-task');});
test('activation: unsupported map/ranking/calculator/filter/planner omit',()=>{const checks=[['L02','unsupported'],['D02','unsupported'],['X04','unsupported'],['X01','unsupported'],['X05','unsupported']] as const; for(const [id,support] of checks) assert.equal(resolvePrimitiveActivation({primitiveId:id,status:'conditional',reason:''},support),'omit');});
test('candidate construction uses canonical IDs only',()=>{const ids=buildPrimitiveCandidates({query:'x',playerProblem:'x',primaryTask:'location'},'P5').map(x=>x.primitiveId); assert.deepEqual(ids,['A01','L01','L02','L03']); assert.equal(ids.includes('G01'),false);});
