import assert from 'node:assert/strict';
import test from 'node:test';
import { PRIMITIVE_DEFINITIONS, renderIncludedPrimitives, renderPrimitive } from '../../src/v4/primitives';
import { createPageData, PRIMITIVE_PAYLOAD_REQUIRED_FIELDS } from '../../src/v4/page-data-contract';
import { resolveIntent } from '../../src/v4/intent-resolver';
import { calculateLinear, filterPrimitiveRows, selectMapMarker, togglePlannerSlot } from '../../src/v4/interactive';

test('V4 exposes exactly the frozen 26 Primitive IDs',()=>{assert.deepEqual(PRIMITIVE_DEFINITIONS.map(x=>x.id),['A01','A02','A03','S01','S02','S03','S04','E01','E02','E03','D01','D02','D03','P01','P02','P03','P04','L01','L02','L03','X01','X02','X03','X04','X05','N01']);});
test('all 26 canonical IDs have explicit payload field schemas',()=>{assert.deepEqual(Object.keys(PRIMITIVE_PAYLOAD_REQUIRED_FIELDS).sort(),PRIMITIVE_DEFINITIONS.map(x=>x.id).sort()); for(const fields of Object.values(PRIMITIVE_PAYLOAD_REQUIRED_FIELDS)) assert.ok(fields.length>0);});
test('primitive instances preserve typed payload and interaction metadata',()=>{const page=createPageData({page:{id:'planner',title:'Planner',href:'/planner/'},intent:resolveIntent({query:'build planner',playerProblem:'arrange a build',primaryTask:'tool-database'}),primitiveSupport:{X01:'available',X02:'available',X05:'available'},primitiveData:[{instanceId:'rows',primitiveId:'E03',payload:{columns:[{id:'name',label:'Name'}],rows:[{name:'Build A'}]},evidenceRefs:[],mediaRefs:[]},{instanceId:'workspace',primitiveId:'X05',payload:{state:{slot:'1'},controls:[],saveShare:{saved:false}},evidenceRefs:[],mediaRefs:[]}]}); const item=renderPrimitive(page,'X05'); assert.equal(item?.interactive,true); assert.equal(item?.instanceId,'workspace'); assert.deepEqual(renderIncludedPrimitives(page).map(x=>x.id),['A01','X01','X02','E03','X05'].filter(id=>page.primitiveData.some(x=>x.primitiveId===id)));});
test('included rendering preserves separate payloads for repeated Primitive IDs',()=>{const page=createPageData({page:{id:'entity',title:'Entity',href:'/entity/'},intent:resolveIntent({query:'entity facts',playerProblem:'look up an entity',primaryTask:'entity-lookup'}),primitiveData:[{instanceId:'facts-a',primitiveId:'E01',payload:{facts:[{label:'Type',value:'Resource'}]},evidenceRefs:[],mediaRefs:[]},{instanceId:'facts-b',primitiveId:'E01',payload:{facts:[{label:'Use',value:'Forge'}]},evidenceRefs:[],mediaRefs:[]}]}); const facts=renderIncludedPrimitives(page).filter((item)=>item.id==='E01'); assert.deepEqual(facts.map((item)=>item.instanceId),['facts-a','facts-b']); assert.deepEqual(facts.map((item)=>item.payload),[{facts:[{label:'Type',value:'Resource'}]},{facts:[{label:'Use',value:'Forge'}]}]);});
test('functional Primitive interactions execute for filter, map, calculator, and planner',()=>{const rows=[{name:'Cinder Axe',class:'Warden'},{name:'Frost Staff',class:'Arcanist'}]; assert.deepEqual(filterPrimitiveRows(rows,'warden'),[rows[0]]); assert.deepEqual(selectMapMarker([{label:'Vein'}],0),{label:'Vein'}); assert.equal(calculateLinear(2,3,4),14); assert.deepEqual(togglePlannerSlot([], 'primary'),['primary']);});
